/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mUJGRo00WeI
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function PillWithX({
  label,
  xButtonHref,
}: {
  label: string;
  xButtonHref: string;
}) {
  return (
    <div className="inline-flex items-center justify-center px-2 py-1 text-sm font-semibold text-black bg-white border border-black rounded-md">
      {label}
      <Link href={xButtonHref}>
        <Button className="ml-2 h-5 w-5 p-1" variant="ghost">
          <IconX className="w-3 h-3" />
        </Button>
      </Link>
    </div>
  );
}

function IconX(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
