
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Na3pRoz8eeC
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { PillWithX } from "./pill-with-x";

export function Repositories() {
  // TODO get from URL
  const repos = [
    "DataDog/serverless-plugin-datadog",
    "DataDog/datadog-cdk-constructs",
  ];
  return (
    <div>
      <div className="flex overflow-x-auto items-center gap-2">
        {repos.map((repo) => (
          <PillWithX key={repo} label={repo} />
        ))}
        <Input
          className="w-32 mr-1"
          id="new-item"
          placeholder="Add repo URL"
          type="text"
        />
        <Button
          className="border border-gray-300 dark:border-gray-700"
          type="submit"
          variant="ghost"
        >
          <IconPlus className="w-4 h-4 text-gray-500" />
        </Button>
      </div>
    </div>
  );
}

function IconPlus(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}
