/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Na3pRoz8eeC
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";

export function Repositories() {
  return (
    <div>
      <div className="flex overflow-x-auto items-center gap-2">
        <span className="whitespace-nowrap px-3 py-1 text-sm font-medium text-gray-700 bg-gray-200 rounded-full dark:text-gray-300 dark:bg-gray-700">
          Item 1
        </span>
        <span className="whitespace-nowrap px-3 py-1 text-sm font-medium text-gray-700 bg-gray-200 rounded-full dark:text-gray-300 dark:bg-gray-700">
          Item 2
        </span>
        <span className="whitespace-nowrap px-3 py-1 text-sm font-medium text-gray-700 bg-gray-200 rounded-full dark:text-gray-300 dark:bg-gray-700">
          Item 3
        </span>
        <Input
          className="flex-grow mr-1"
          id="new-item"
          placeholder="Add GitHub repo URL"
          type="text"
        />
        <Button
          className="border border-gray-300 dark:border-gray-700"
          type="submit"
          variant="ghost"
        >
          <IconPlus className="w-4 h-4 text-gray-500" />
        </Button>
      </div>
    </div>
  );
}

function IconPlus(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}
