"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Na3pRoz8eeC
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { PillWithX } from "./pill-with-x";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import Link from "next/link";

export function Repositories() {
  // Comment to trigger build
  const searchParams = useSearchParams();
  const reposParam = searchParams.getAll("repo") ?? [];

  const repos = Array.isArray(reposParam) ? reposParam : [reposParam];

  const [textBoxContent, setTextBoxContent] = useState("");

  const newRepo = textBoxContent.replace("https://github.com/", "");

  const urlWithNewRepo =
    repos.length === 0
      ? `/?repo=${newRepo}`
      : `/?repo=${repos.join("&repo=")}&repo=${newRepo}`;

  return (
    <div className="flex">
      <div className="flex overflow-x-auto items-center gap-2 flex-wrap">
        {repos.map((repo) => {
          const urlWithoutRepo = `/?repo=${repos
            .filter((r) => r !== repo)
            .join("&repo=")}`;
          return (
            <PillWithX key={repo} label={repo} xButtonHref={urlWithoutRepo} />
          );
        })}
      </div>
      <div className="flex ml-2 items-center">
        <Input
          size={1}
          className="w-40 mr-1"
          id="new-item"
          placeholder="Add repo URL"
          type="text"
          value={textBoxContent}
          onChange={(e) => setTextBoxContent(e.target.value)}
        />
        <Link href={textBoxContent === "" ? "#" : urlWithNewRepo}>
          <Button
            size="sm"
            className="hover:bg-gray-200"
            type="submit"
            variant="ghost"
            disabled={
              !textBoxContent.startsWith("https://github.com/") ||
              repos.includes(textBoxContent.replace("https://github.com/", ""))
            }
          >
            <IconPlus className="w-4 h-4 text-gray-500 " />
          </Button>
        </Link>
      </div>
    </div>
  );
}

function IconPlus(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}
